python train_maxent.py \
--dataset cifar100small2k \
--model resnet18 \
--data_augmentation \
--lambd 0.2 \
--run_id MPE  \
--learning_rate 0.1 \
--label_smoothing_factor 0.6 \
--batch_size 32 \
--attack_iters 1 \
--alpha 0.5 \
--epsilon 0.5 \
--seed 10